insert into public.advertising_packages (
  organization_id,
  package_key,
  version,
  name,
  status,
  market,
  placement_scope,
  price_cents,
  currency,
  term_days,
  ad_length_seconds,
  frequency_label,
  loop_share,
  screen_count,
  projected_plays,
  projection_period_days,
  availability_status,
  metadata,
  activated_at
)
values
(
  '28ad55e4-d32d-423b-80b5-481bd15dec9e',
  'founding-single',
  1,
  'Founding Single',
  'active',
  'Grand Strand',
  '{"mode":"single_screen","selection":"best_available","commissioned_only":true}'::jsonb,
  14900,
  'usd',
  30,
  15,
  'One ad position in the CoastLoop loop on one commissioned screen',
  null,
  1,
  null,
  null,
  'limited',
  '{"badge":"START HERE","reporting":"verified delivery","founding_offer":true,"creative_included":true}'::jsonb,
  '2026-09-07 19:10:30.338538+00'::timestamptz
),
(
  '28ad55e4-d32d-423b-80b5-481bd15dec9e',
  'local-three',
  1,
  'Local Three',
  'active',
  'Grand Strand',
  '{"mode":"multi_screen","selection":"best_available","max_screens":3,"commissioned_only":true}'::jsonb,
  29900,
  'usd',
  30,
  15,
  'One ad position in the CoastLoop loop across up to three commissioned screens',
  null,
  3,
  null,
  null,
  'limited',
  '{"badge":"MOST POPULAR","reporting":"verified delivery","founding_offer":true,"creative_included":true}'::jsonb,
  '2026-09-07 19:10:30.338538+00'::timestamptz
),
(
  '28ad55e4-d32d-423b-80b5-481bd15dec9e',
  'founding-network',
  1,
  'Founding Network',
  'active',
  'Grand Strand',
  '{"mode":"network","selection":"all_eligible_live_inventory","commissioned_only":true}'::jsonb,
  49900,
  'usd',
  30,
  15,
  'Network rotation across all eligible commissioned CoastLoop screens in the selected market',
  null,
  null,
  null,
  null,
  'limited',
  '{"badge":"OWN THE LOOP","reporting":"verified delivery","founding_offer":true,"creative_included":true}'::jsonb,
  '2026-09-07 19:10:30.338538+00'::timestamptz
)
on conflict (organization_id, package_key, version) do nothing;
